### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by NeonNinjaCat** [DaveDuck321/SmashIt#5]
the 1337 kahoot team patched all 3 modes including smash

**Comment by DaveDuck321** [comment]
Quickly tested on my phone, it looks like you're right. I'll investigate it later today

**Comment by NeonNinjaCat** [comment]
Thanks i attempted to debug it and im pretty sure i got a few errors but im not too good with developing so idk

**Comment by DaveDuck321** [comment]
Sorry, I forgot about this. I've fixed it now though
